import type { Distribution, DistributionDetail } from "../models/Beneficiary";

export const distributions: Distribution[] = [
  {
    id: 'dst--001',
    region: 'West Nile',
    date: '2025-06-15',
    status: 'Planned',
    beneficiaries: 1000,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
  {
    id: 'dst--002',
    region: 'Eastern Province',
    date: '2025-06-10',
    status: 'Completed',
    beneficiaries: 850,
    aidType: 'Medical',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--003',
    region: 'Northern Region',
    date: '2025-07-01',
    status: 'Ongoing',
    beneficiaries: 950,
    aidType: 'Shelter',
    deliveryChannel: 'Mobile Units',
  },
  {
    id: 'dst--004',
    region: 'Central District',
    date: '2025-06-20',
    status: 'Planned',
    beneficiaries: 600,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--005',
    region: 'Southern Plains',
    date: '2025-07-10',
    status: 'Completed',
    beneficiaries: 1300,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
  {
    id: 'dst--006',
    region: 'Lake Zone',
    date: '2025-06-25',
    status: 'Ongoing',
    beneficiaries: 700,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Units',
  },
  {
    id: 'dst--007',
    region: 'Highland Area',
    date: '2025-07-05',
    status: 'Planned',
    beneficiaries: 400,
    aidType: 'Education',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--008',
    region: 'Coastal Belt',
    date: '2025-06-30',
    status: 'Completed',
    beneficiaries: 1100,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
  {
    id: 'dst--009',
    region: 'River Valley',
    date: '2025-07-12',
    status: 'Ongoing',
    beneficiaries: 500,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--010',
    region: 'Urban Center',
    date: '2025-07-15',
    status: 'Planned',
    beneficiaries: 2000,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Units',
  },
  {
    id: 'dst--011',
    region: 'Mountain Region',
    date: '2025-07-18',
    status: 'Completed',
    beneficiaries: 750,
    aidType: 'Shelter',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--012',
    region: 'Desert Fringe',
    date: '2025-07-20',
    status: 'Ongoing',
    beneficiaries: 300,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
];

export const distributionDetails: Record<string, DistributionDetail> = {
  'dst--001': {
    id: 'dst--001',
    region: 'West Nile',
    date: '2025-06-15',
    status: 'Planned',
    beneficiaries: 1200,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--001', name: 'Jane Doe' },
      { id: 'bnf--002', name: 'John Smith' },
    ],
  },
  'dst--002': {
    id: 'dst--002',
    region: 'Eastern Province',
    date: '2025-06-10',
    status: 'Completed',
    beneficiaries: 850,
    aidType: 'Medical',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--003', name: 'Alice Brown' },
      { id: 'bnf--004', name: 'Bob White' },
    ],
  },
  'dst--003': {
    id: 'dst--003',
    region: 'Northern District',
    date: '2025-06-20',
    status: 'Ongoing',
    beneficiaries: 500,
    aidType: 'Water',
    deliveryChannel: 'Mobile Units',
    beneficiaryList: [
      { id: 'bnf--005', name: 'Carlos Green' },
      { id: 'bnf--006', name: 'Fatima Noor' },
    ],
  },
  'dst--004': {
    id: 'dst--004',
    region: 'Southern Plains',
    date: '2025-06-25',
    status: 'Planned',
    beneficiaries: 400,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--007', name: 'Liam Chen' },
      { id: 'bnf--008', name: 'Sara Ahmed' },
    ],
  },
  'dst--005': {
    id: 'dst--005',
    region: 'Central Valley',
    date: '2025-07-01',
    status: 'Completed',
    beneficiaries: 950,
    aidType: 'Medical',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--009', name: 'Emily Davis' },
      { id: 'bnf--010', name: 'Mohammed Ali' },
    ],
  },
  'dst--006': {
    id: 'dst--006',
    region: 'Coastal Area',
    date: '2025-07-05',
    status: 'Ongoing',
    beneficiaries: 600,
    aidType: 'Shelter',
    deliveryChannel: 'Mobile Units',
    beneficiaryList: [
      { id: 'bnf--011', name: 'Olga Petrova' },
      { id: 'bnf--012', name: 'Samuel Kim' },
    ],
  },
  'dst--007': {
    id: 'dst--007',
    region: 'Highland Zone',
    date: '2025-07-10',
    status: 'Planned',
    beneficiaries: 700,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--013', name: 'Amina Yusuf' },
      { id: 'bnf--014', name: 'Lucas Rossi' },
    ],
  },
  'dst--008': {
    id: 'dst--008',
    region: 'River Basin',
    date: '2025-07-12',
    status: 'Completed',
    beneficiaries: 1100,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--015', name: 'Priya Singh' },
      { id: 'bnf--016', name: 'David Lee' },
    ],
  },
  'dst--009': {
    id: 'dst--009',
    region: 'Urban Center',
    date: '2025-07-14',
    status: 'Ongoing',
    beneficiaries: 800,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Units',
    beneficiaryList: [
      { id: 'bnf--017', name: 'Maria Garcia' },
      { id: 'bnf--018', name: 'James Wilson' },
    ],
  },
  'dst--010': {
    id: 'dst--010',
    region: 'Lake District',
    date: '2025-07-16',
    status: 'Planned',
    beneficiaries: 650,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--019', name: 'Chen Wei' },
      { id: 'bnf--020', name: 'Nia Johnson' },
    ],
  },
  'dst--011': {
    id: 'dst--011',
    region: 'Mountain Region',
    date: '2025-07-18',
    status: 'Completed',
    beneficiaries: 750,
    aidType: 'Shelter',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--021', name: 'Omar Farouk' },
      { id: 'bnf--022', name: 'Sophia Martinez' },
    ],
  },
  'dst--012': {
    id: 'dst--012',
    region: 'Desert Fringe',
    date: '2025-07-20',
    status: 'Ongoing',
    beneficiaries: 300,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--023', name: 'Ahmed Hassan' },
      { id: 'bnf--024', name: 'Julia Novak' },
    ],
  },
}; 